import { createStyles, Theme } from "@material-ui/core/styles";

export default (theme: Theme) =>
  createStyles({
    root: {
      display: "flex",
    },
    section_style: {
      backgroundColor: "#E7FCF1",
      paddingTop: theme.spacing(5),
      paddingBottom: theme.spacing(20),
    },
    h1_style: {
      color: "#343D48",
      fontFamily: "Okta",
      fontSize: 94,
      fontWeight: "bold",
      fontStyle: "italic",
    },
    h1_banner_style: {
      color: "#16DE74",
      fontFamily: "Okta",
      fontSize: 94,
      fontWeight: "bold",
      fontStyle: "italic",
    },
    subtitle_style: {
      color: "#343D48",
      fontFamily: "Okta",
      fontSize: 18,
      fontWeight: "bold",
      fontStyle: "italic",
      marginTop: theme.spacing(3),
      // marginBottom: theme.spacing(3),
      maxWidth: theme.spacing(50),
    },
    subtitle2_style: {
      color: "#343D48",
      fontFamily: "Okta",
      fontSize: 18,
      fontWeight: "bold",
      fontStyle: "italic",
      // marginTop: theme.spacing(3),
      // marginBottom: theme.spacing(3),
      maxWidth: theme.spacing(70),
    },
    btn_searach: {
      height: "100%",
      width: "100%",
      marginTop: theme.spacing(4),
      // marginLeft: 50,
      // marginRight: 50,
    },
    paper: {
      padding: theme.spacing(2),
      textAlign: "center",
      color: theme.palette.text.secondary,
    },
    city_style: {
      position: "absolute",
      maxHeight: 900,
      maxwidth: "100%",
      top: 60,
      right: 40, //80
      zIndex: 1,
    },
    location_12_style: {
      maxWidth: 85,
      position: "absolute",
      right: 730,
      top: 440,
      zIndex: 4,
    },
    location_9_style: {
      maxWidth: 110,
      position: "absolute",
      right: 450,
      top: 550,
      zIndex: 4,
    },
    location_10_style: {
      maxWidth: 120,
      position: "absolute",
      right: 190,
      top: 450,
      zIndex: 4,
    },
    dog_style: {
      position: "absolute",
      maxHeight: 700,
      maxwidth: "100%",
      right: 190,
      top: 190,
      zIndex: 3,
    },
    cat_style: {
      position: "absolute",
      maxHeight: 550,
      maxwidth: "100%",
      right: 510,
      top: 320,
      zIndex: 3,
    },
    bird_style: {
      position: "absolute",
      maxHeight: 100,
      maxwidth: "100%",
      right: 690,
      top: 390,
      zIndex: 3,
    },
    building_8_style: {
      position: "absolute",
      maxHeight: 350,
      maxwidth: "100%",
      right: 35,
      top: 450,
      zIndex: 4,
    },
    building_7_style: {
      position: "absolute",
      maxHeight: 260,
      maxwidth: "100%",
      right: 530,
      top: 550,
      zIndex: 4,
    },
    building_path_12_style: {
      position: "absolute",
      maxHeight: 180,
      maxwidth: "100%",
      right: 0,
      top: 400,
      zIndex: 2,
    },
    building_path_11_style: {
      position: "absolute",
      maxHeight: 200,
      maxwidth: "100%",
      right: 50,
      top: 430,
      zIndex: 2,
    },
    building_path_10_style: {
      position: "absolute",
      maxHeight: 250,
      maxwidth: "100%",
      right: 0,
      top: 580,
      zIndex: 2,
    },
  });
